### ISSUE TITLE
Base setting

### ISSUE THREAD

**Issue by robert-min** [C-auto/cafe_operation_java_migration#2]
### To do list
- [x] Multi module (api, db)
- [x] swagger
- [x] snackCase base setting
- [x] Logger
- [x] Success response
- [x] Error response
- [x] Api exception

**Comment by robert-min** [comment]
## DB JPA 설정
- `ddl-auto: validation` 옵션으로 서버 실행시 DB 정상 연결 확인

```yaml

spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://{{ db_server_url }}:3306/{{ table_name }}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {{ db_user_name }}
    password: {{ db_password }}
```
